interface BorrowRequests {
    id: string,
    name?: string,
    email?: string,
    college?: College,
    role?: Role,
    borrowDate: Date,
    returnDate: Date,
    purpose: string,
    borrowStatus: BorrowStatus,
    condition: Condition,
    note: string,
    userId: string,
    createdAt: Date,
    updatedAt?: Date,
    cartId: string,
}