import { PrismaClient } from '@prisma/client';
import { ObjectId } from 'mongodb';
import prisma from '@/utils/prisma';

const users: User[] = [
    {
        id: new ObjectId().toString(),
        firstname: 'Michael Gerald',
        lastname: 'Antaran',
        email: 'michaelgerald.antaran@cvsu.edu.ph',
        role: 'Student',
        college: 'CEIT',
    },
    {
        id: new ObjectId().toString(),
        firstname: 'Charles Dave',
        lastname: 'Arevalo',
        email: 'charlesdave.arevalo@cvsu.edu.ph',
        role: 'Student',
        college: 'CEIT',
    },
    {
        id: new ObjectId().toString(),
        firstname: 'Ralph Howard',
        lastname: 'Azarcon',
        email: 'ralphhoward.azarcon@cvsu.edu.ph',
        role: 'Student',
        college: 'CEIT',
    },
    {
        id: new ObjectId().toString(),
        firstname: 'Jessa Marie',
        lastname: 'Babaan',
        email: 'jessamarie.babaan@cvsu.edu.ph',
        role: 'Student',
        college: 'CEIT',
    },
    {
        id: new ObjectId().toString(),
        firstname: 'Kirsten Rachelle',
        lastname: 'Baybay',
        email: 'kirstenrachelle.baybay@cvsu.edu.ph',
        role: 'Student',
        college: 'CEIT',
    },
    {
        id: new ObjectId().toString(),
        firstname: 'Christian Arby',
        lastname: 'Camama',
        email: 'christianarby.camama@cvsu.edu.ph',
        role: 'Student',
        college: 'CEIT',
    },
    {
        id: new ObjectId().toString(),
        firstname: 'Josh Ivan',
        lastname: 'Caramat',
        email: 'joshivan.caramat@cvsu.edu.ph',
        role: 'Student',
        college: 'CEIT',
    },
    {
        id: new ObjectId().toString(),
        firstname: 'Gabriella Wydeline',
        lastname: 'Cayanan',
        email: 'gabriellawydeline.cayanan@cvsu.edu.ph',
        role: 'Student',
        college: 'CEIT',
    },
    {
        id: new ObjectId().toString(),
        firstname: 'Alian Gem Axel',
        lastname: 'Crooc',
        email: 'aliangemaxel.crooc@cvsu.edu.ph',
        role: 'Student',
        college: 'CEIT',
    },
    {
        id: new ObjectId().toString(),
        firstname: 'Daniel Lawrence',
        lastname: 'Cunanan',
        email: 'daniellawrence.cunanan@cvsu.edu.ph',
        role: 'Student',
        college: 'CEIT',
    },
    {
        id: new ObjectId().toString(),
        firstname: 'Harvy',
        lastname: 'Dela Cruz',
        email: 'harvy.delacruz@cvsu.edu.ph',
        role: 'Student',
        college: 'CEIT',
    },
    {
        id: new ObjectId().toString(),
        firstname: 'Nicolette Jane',
        lastname: 'Dela Cruz',
        email: 'nicalettejane.delacruz@cvsu.edu.ph',
        role: 'Student',
        college: 'CEIT',
    },
    {
        id: new ObjectId().toString(),
        firstname: 'Princess Leila',
        lastname: 'Ditchon',
        email: 'princessleila.ditchon@cvsu.edu.ph',
        role: 'Student',
        college: 'CEIT',
    },
    {
        id: new ObjectId().toString(),
        firstname: 'John Joshua',
        lastname: 'Garcia',
        email: 'johnjoshua.garcia@cvsu.edu.ph',
        role: 'Student',
        college: 'CEIT',
    },
    {
        id: new ObjectId().toString(),
        firstname: 'Darrem',
        lastname: 'Gonzaga',
        email: 'darrem.gonzaga@cvsu.edu.ph',
        role: 'Student',
        college: 'CEIT',
    },
    {
        id: new ObjectId().toString(),
        firstname: 'Sophia',
        lastname: 'Gutierrez',
        email: 'sophia.gutierrez@cvsu.edu.ph',
        role: 'Student',
        college: 'CEIT',
    },
    {
        id: new ObjectId().toString(),
        firstname: 'Lorenzo',
        lastname: 'Laforteza',
        email: 'lorenzo.laforteza@cvsu.edu.ph',
        role: 'Student',
        college: 'CEIT',
    },
    {
        id: new ObjectId().toString(),
        firstname: 'Mark Norenz',
        lastname: 'Laurito',
        email: 'marknorenz.laurito@cvsu.edu.ph',
        role: 'Student',
        college: 'CEIT',
    },
    {
        id: new ObjectId().toString(),
        firstname: 'Zildjian Lee',
        lastname: 'Loren',
        email: 'zildjianlee.loren@cvsu.edu.ph',
        role: 'Student',
        college: 'CEIT',
    },
    {
        id: new ObjectId().toString(),
        firstname: 'Precios Jewel',
        lastname: 'Mabunga',
        email: 'preciosjewel.mabunga@cvsu.edu.ph',
        role: 'Student',
        college: 'CEIT',
    },
    {
        id: new ObjectId().toString(),
        firstname: 'Zymon Clark',
        lastname: 'Mendoza',
        email: 'zymonclark.mendoza@cvsu.edu.ph',
        role: 'Student',
        college: 'CEIT',
    },
    {
        id: new ObjectId().toString(),
        firstname: 'Jaimee Rose',
        lastname: 'Mercado',
        email: 'jaimeerose.mercado@cvsu.edu.ph',
        role: 'Student',
        college: 'CEIT',
    },
    {
        id: new ObjectId().toString(),
        firstname: 'Jan Marichie',
        lastname: 'Mojica',
        email: 'janmarichie.mojica@cvsu.edu.ph',
        role: 'Student',
        college: 'CEIT',
    },
    {
        id: new ObjectId().toString(),
        firstname: 'Kurt Patrick Wes',
        lastname: 'Moleno',
        email: 'kurtpatrickwes.moleno@cvsu.edu.ph',
        role: 'Student',
        college: 'CEIT',
    },
    {
        id: new ObjectId().toString(),
        firstname: 'Arjhon',
        lastname: 'Monsalud',
        email: 'arjhon.monsalud@cvsu.edu.ph',
        role: 'Student',
        college: 'CEIT',
    },
    {
        id: new ObjectId().toString(),
        firstname: 'Shania Gwyneth',
        lastname: 'Nuga',
        email: 'shaniagwyneth.nuga@cvsu.edu.ph',
        role: 'Student',
        college: 'CEIT',
    },
    {
        id: new ObjectId().toString(),
        firstname: 'John Archie',
        lastname: 'Patawe',
        email: 'johnarchie.patawe@cvsu.edu.ph',
        role: 'Student',
        college: 'CEIT',
    },
    {
        id: new ObjectId().toString(),
        firstname: 'Ashly',
        lastname: 'Pusa',
        email: 'ashly.pusa@cvsu.edu.ph',
        role: 'Student',
        college: 'CEIT',
    },
    {
        id: new ObjectId().toString(),
        firstname: 'Dinothelo',
        lastname: 'Quiroga',
        email: 'dinothelo.quiroga@cvsu.edu.ph',
        role: 'Student',
        college: 'CEIT',
    },
    {
        id: new ObjectId().toString(),
        firstname: 'John Herson',
        lastname: 'Radones',
        email: 'johnherson.radones@cvsu.edu.ph',
        role: 'Student',
        college: 'CEIT',
    },
    {
        id: new ObjectId().toString(),
        firstname: 'Edrei Reigne',
        lastname: 'Rivera',
        email: 'edreireigne.rivera@cvsu.edu.ph',
        role: 'Student',
        college: 'CEIT',
    },
    {
        id: new ObjectId().toString(),
        firstname: 'Michaela',
        lastname: 'Roderno',
        email: 'michaela.roderno@cvsu.edu.ph',
        role: 'Student',
        college: 'CEIT',
    },
    {
        id: new ObjectId().toString(),
        firstname: 'Bernard',
        lastname: 'Sapida',
        email: 'bernard.sapida@cvsu.edu.ph',
        role: 'Admin',
        college: 'CSPEAR',
    },
    {
        id: new ObjectId().toString(),
        firstname: 'Prince',
        lastname: 'Simons',
        email: 'prince.simons@cvsu.edu.ph',
        role: 'Student',
        college: 'CEIT',
    },
    {
        id: new ObjectId().toString(),
        firstname: 'Josh Elland',
        lastname: 'Sombrano',
        email: 'joshelland.sombrano@cvsu.edu.ph',
        role: 'Student',
        college: 'CEIT',
    },
    {
        id: new ObjectId().toString(),
        firstname: 'Iresh Abbegail',
        lastname: 'Sumayang',
        email: 'ireshabbegail.sumayang@cvsu.edu.ph',
        role: 'Admin',
        college: 'CSPEAR',
    },
    {
        id: new ObjectId().toString(),
        firstname: 'Ivan Neil',
        lastname: 'Tapel',
        email: 'ivanneil.tapel@cvsu.edu.ph',
        role: 'Student',
        college: 'CEIT',
    },
    {
        id: new ObjectId().toString(),
        firstname: 'Aaron Vincent',
        lastname: 'Villaluz',
        email: 'aaronvincent.villaluz@cvsu.edu.ph',
        role: 'Student',
        college: 'CEIT',
    },
];

export const populateUsers = async () => {
    await prisma.users.deleteMany();

    // for (let user of users) {

    const createdUser = await prisma.users.createMany({
        data: [
            {
                id: new ObjectId('6555a86c47783f96117a0324').toString(),
                clerkUserId: 'user_2XqiORxGDitSYzmSKhuMOWGftLw',
                firstname: 'Bernard',
                lastname: 'Sapida',
                email: 'bernard.sapida@cvsu.edu.ph',
                role: 'Admin',
                college: 'CSPEAR',
            },
            {
                id: new ObjectId('6555a86c47783f96117a0325').toString(),
                clerkUserId: 'user_2Y4QxBl11OeY0bCGVRtV1gfNNnc',
                firstname: 'Bernard',
                lastname: 'Sapida',
                email: 'bernardsapida1706@gmail.com',
                role: 'Student',
                college: 'CEIT',
            }
        ]
    });

    console.log(createdUser);

    // }
}
